### ISSUE TITLE
ios_selectors.test.robot test failing for iPad Pro (12.9-inch) (4th generation)

### ISSUE THREAD

**Issue by AmitKulkarni9** [serhatbolsu/robotframework-appium-sample#1]
Hi serhatbolsu,

Nice work with this example to setup Mobile test automation up and running with Robotframework. 
It worked smoothly without any issue. Just a minor issue observed while running test
ios_selectors.test.robot test failing for iPad Pro (12.9-inch) (4th generation)
Should find elements by nspredicate                                   | FAIL |
ValueError: Element locator 'nsp=visible = 1' did not match any elements.

**Comment by serhatbolsu** [comment]
Thank you @AmitKulkarni9  as this is minor I will mark it closed, since this is an example library
